version: '3.9'

services:
    database:
        image: mariadb:latest
        ports:
            - 3306:3306
        volumes:
            - ./.data/mariadb:/var/lib/mysql
        environment:
            - TZ=${TIMEZONE}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=root
