@startuml sequence
actor   User
participant User order 1
participant UserCenter as App order 2
participant "Line Platform" as Line order 3
User -> App: Log in
App -> Line: Access the Line Login authorization \nURL with `redirect_uri` and `state`
User <- Line: Line Login screen
User -> Line: Authentication
User <- Line: Consent screen
User -> Line: Authorization
App <- Line: Access `redirect_uri` with `state` \nand authorization code
App -> Line: Request access token & id token
App <-- Line: Access token & id token
App -> Line: Parse id token
App <-- Line: JWT info
App -> App: Authentication with user Line ID
User <- App: Redirect to home page
@enduml
